spring.application.name=order_service
server.port=8081

spring.datasource.url=jdbc:postgresql://postgres-order:5432/order_db
spring.datasource.username=admin
spring.datasource.password=admin

spring.kafka.bootstrap-servers=kafka:9093
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

grpc.client.inventory-service.address=static://inventory-service:9090
grpc.client.inventory-service.negotiationType=PLAINTEXT

internal.api.key=secret-api-key
logging.pattern.level=%5p [${spring.application.name:},%X{X-Trace-Id:-}]