spring.application.name=order_service
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5434/order_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jpa.hibernate.ddl-auto=none
jpa.hibernate.show-sql=true
spring.liquibase.change-log=db.changelog/db.changelog-master.xml

jwt.secret=Vy9zGq5j2kL8pRt3nB7wXe1yQ6mJ4hF0dC2aK9sN8vU1=
jwt.access.expiration.ms=900000
jwt.refresh.expiration.ms=604800000

grpc.client.inventory-service.address=static://localhost:9090
grpc.client.inventory-service.negotiationType=PLAINTEXT

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer