spring.application.name=inventory_service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/inventory_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jpa.hibernate.ddl-auto=none
jpa.hibernate.show-sql=true
spring.liquibase.change-log=db.changelog/db.changelog-master.xml

grpc.server.port=9090

logging.pattern.level=%5p [${spring.application.name:},%X{X-Trace-Id:-}]

internal.api.key=secret-api-key