spring.application.name=notification_service
server.port=8083

spring.datasource.url=jdbc:postgresql://postgres-notification:5432/notification_db
spring.datasource.username=admin
spring.datasource.password=admin

spring.kafka.bootstrap-servers=kafka:9093

internal.api.key=secret-api-key
logging.pattern.level=%5p [${spring.application.name:},%X{X-Trace-Id:-}]